### ISSUE TITLE
parameter 'subLevels' doesn't work 

### ISSUE THREAD

**Issue by neebel** [johnno1962/SwiftTrace#42]
SwiftTrace.traceMainBundle(subLevels: 3) 

when i set  parameter 'subLevels' to 3, all methods are traced, not top 3 level methods.

public func f1() {
     f2()
}

public func f2() {
   f3()
}

public func f3() {
  f4()
}

public func f4() {

}

I expect f1、f2、f3 are traced and f4 are not traced, what can I to do?

**Comment by johnno1962** [comment]
Hi, I'm afraid subLevels isn't entirely thought out or implemented and it's a long time since I've looked at it. IIRC, the idea was if you are filtering by instance or class you can bring in the trace of N sub levels of calls below a qualifying call. In this case, as there is no filtering the counter is continually reset. Is getting this working important to you? How would you have it work?
```Swift
                if (swizzle.trace.instanceFilter == nil ||
                    swizzle.trace.instanceFilter == swiftSelf) &&
                    (swizzle.trace.classFilter == nil ||
                     swizzle.trace.classFilter === swizzle.getClass()) {
                    threadLocal.levelsTracing = swizzle.trace.subLevels
                    return true
                }
 ```
The idea was you could use filters to select out methods you were interested in and also see the methods they called e.g.
```Swift
class C: NSObject {
    var t = "t"
    lazy var c = C()
    func f() {}
    public func f1() {
        c.f2()
    }

    public func f2() {
        c.f3()
    }

    public func f3() {
        c.f4()
    }

    public func f4() {

    }

}
...
        let c = C()
        c.swiftTraceInstance(withSubLevels: 3)
        c.f1()
